CREATE OR REPLACE FILE FORMAT DEV.AMBYINT_COM_SCHEMA.JSON_FORMAT
	TYPE = JSON
	NULL_IF = ()
;
CREATE OR REPLACE FILE FORMAT DEV.AMBYINT_COM_SCHEMA.JSON_STRIP_OUTER_ARRAY_FORMAT
	TYPE = JSON
	NULL_IF = ()
	STRIP_OUTER_ARRAY = TRUE
;