USE SCHEMA REP_VIEW;

CREATE OR REPLACE PROCEDURE check_sp()
RETURNS FLOAT
LANGUAGE SQL
AS
$$
BEGIN
  IF (CURRENT_DATABASE() ='DEV') THEN
    CREATE or replace TABLE DEV_TB(FIRST_NAME VARCHAR,LAST_NAME VARCHAR);
  ELSEIF (CURRENT_DATABASE() ='QA') THEN
    CREATE or replace TABLE QA_TB(FIRST_NAME VARCHAR,LAST_NAME VARCHAR);
  ELSE
    CREATE or replace TABLE PROD_TB(FIRST_NAME VARCHAR,LAST_NAME VARCHAR);
  END IF;
END;
$$
;


call check_sp();