USE SCHEMA REP_VIEW;

CREATE OR REPLACE PROCEDURE cr_tbl()
RETURNS FLOAT
LANGUAGE SQL
AS
$$
BEGIN
  IF (CURRENT_DATABASE() ='DEV') THEN
    CREATE or replace TABLE DEV_TBL(FIRST_NAME VARCHAR,LAST_NAME VARCHAR);
  ELSEIF (CURRENT_DATABASE() ='QA') THEN
    CREATE or replace TABLE QA_TBL(FIRST_NAME VARCHAR,LAST_NAME VARCHAR);
  ELSE
    CREATE or replace TABLE test_TBL(FIRST_NAME VARCHAR,LAST_NAME VARCHAR);
  END IF;
END;
$$
;
