 name: Block Feature Merges
 on:
     pull_request:
       branches:
         - 'QA'
    
 jobs:
     check:
       runs-on: ubuntu-latest
       steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Block feature branch merges
         run: |
           SOURCE_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
           if [ "$SOURCE_BRANCH" != "DEV" ]; then
             echo "Merging from DEV branch is ONLY allowed."
             exit 1
           fi
