name: snowflake-devops-demo-DEV

# Controls when the action will run. 
on:
  pull_request:
   branches:
    - "DEV"
   types: [closed]  
   
   paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
jobs:              
    deploy-snowflake-changes-job-DEV:
      runs-on: ubuntu-latest
      env:
          table1: tablename
      steps:
      - name: variables
        run: |
          if [ "$GITHUB_REF" = "refs/heads/DEV" ]; then
            set table1="tbl_123_wells"
          elif [ "$GITHUB_REF" = "refs/heads/QA" ]; then
            set table1="tbl_wells"
          else
            set table1="tbl_3_wells"
          fi
  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
      
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DEV }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          ENV_WH: ${{secrets.DEV_ENV_WH}}
          
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table

